# GCP Cloud Run Module for MCP Server
#
# Deploys the MCP server as a Cloud Run service with:
# - Auto-scaling (min 0, max configurable)
# - Cloud Monitoring integration
# - Secret Manager integration
# - Optional VPC connector

terraform {
  required_version = ">= 1.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 5.0"
    }
  }
}

locals {
  service_account_id = var.service_account_email != "" ? null : "${var.service_name}-sa"
}

# Service account for Cloud Run
resource "google_service_account" "this" {
  count        = var.service_account_email != "" ? 0 : 1
  account_id   = local.service_account_id
  display_name = "Service account for ${var.service_name}"
  description  = "Used by Cloud Run service ${var.service_name} to access GCP resources"
}

# Cloud Run service
resource "google_cloud_run_service" "this" {
  name     = var.service_name
  location = var.region

  template {
    spec {
      service_account_name = coalesce(var.service_account_email, google_service_account.this[0].email)
      container_concurrency = var.container_concurrency
      timeout_seconds      = var.timeout_seconds

      containers {
        image = var.container_image
        ports {
          name           = "http"
          container_port = var.container_port
        }

        # Environment variables
        dynamic "env" {
          for_each = var.environment_variables
          content {
            name  = env.key
            value = env.value
          }
        }

        # Secret environment variables
        dynamic "env" {
          for_each = var.secret_environment_variables
          content {
            name = env.value.name
            value_source {
              secret_key_ref {
                name  = env.value.secret_name
                key   = env.value.key
              }
            }
          }
        }

        # Resource limits
        resources {
          limits = var.resource_limits
        }
      }
    }

    # Metadata
    metadata {
      annotations = var.annotations
      labels      = var.labels
    }
  }

  # Traffic routing
  traffic {
    percent         = 100
    latest_revision = true
  }

  # Autogenerated project number for IAM
  depends_on = [google_service_account.this]
}

# IAM binding for Cloud Run invoker
resource "google_cloud_run_service_iam_member" "unauthenticated" {
  count    = var.allow_unauthenticated ? 1 : 0
  service  = google_cloud_run_service.this.name
  location = google_cloud_run_service.this.location
  role     = "roles/run.invoker"
  member   = "allUsers"
}

# VPC Connector (optional)
resource "google_vpc_access_connector" "this" {
  count         = var.vpc_connector_name != "" ? 0 : 1
  name          = "${var.service_name}-connector"
  region        = var.region
  network       = var.vpc_network
  ip_cidr_range = var.vpc_connector_cidr
}
